name: Eport pdf
on:
  push:
    branches:
      - master
    paths:
      - '/**.md'
jobs:
  Eport-Pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_dir: ./
          output_dir: pdfs
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: pdfs

