name: Eport pdf
on: [push, workflow_dispatch]
jobs:
  Eport-Pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_dir: /
          output_dir: /pdfs
          build_html: false
      - uses: actions/upload-artifact@v1
        with:
          name: upload
          path: /pdfs

